# Generated by Django 5.0.6 on 2024-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(upload_to='media/principal_images/'),
        ),
    ]
