# Generated by Django 5.0.6 on 2024-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaricon',
            name='icon',
            field=models.ImageField(upload_to='media/icons/'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='media/icons/'),
        ),
    ]
