# Generated by Django 5.0.6 on 2024-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_navbaricon_icon_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaricon',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
