# Generated by Django 5.0.6 on 2024-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sliderimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='image',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image1',
            field=models.ImageField(default='slider/default.jpg', upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image2',
            field=models.ImageField(default='slider/default.jpg', upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image3',
            field=models.ImageField(default='slider/default.jpg', upload_to='slider/'),
        ),
    ]
