# Generated by Django 5.0.6 on 2024-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sliderimage_image_sliderimage_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaricon',
            name='icon',
            field=models.ImageField(default='icons/defaulticon.jpg', upload_to='icons/'),
        ),
    ]
